title: IsomerAI
url: https://www.isomerai.org
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#681891"
  secondary-color: "#91187d"
  media-colors:
    - title: media-color-one
      color: "#2c1891"
    - title: media-color-two
      color: "#681891"
    - title: media-color-three
      color: "#7d1cae"
    - title: media-color-four
      color: "#531374"
    - title: media-color-five
      color: "#7d1cae"
description: An Isomer site of the Singapore Government that provides AI
  solutions to improve everyday lives.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.d24me0rlav2jfo.amplifyapp.com
prod: https://master.dzs0r8o0ewlw7.amplifyapp.com
facebook-pixel: ""
shareicon: /images/isomer-logo.svg
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
